// Generated by the Blazor I18n Text compiler
namespace AboutMe.I18nText
{
    public partial class Footer : global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextFallbackLanguage, global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextLateBinding
    {
        string global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextFallbackLanguage.FallBackLanguage => "en";

        public string this[string key] => global::Toolbelt.Blazor.I18nText.I18nTextExtensions.GetFieldValue(this, key);

        /// <summary>".NET and Android enginner.&lt;br /&gt;Favorite CI are Azure Pipelines and GitHub Actions."</summary>
        public string AboutMe;

        /// <summary>"Blog"</summary>
        public string Blog;

        /// <summary>"This site is using &lt;a href=&quot;http://blazor.net&quot; target=&quot;_blank&quot;&gt;Blazor&lt;/a&gt; technology. Original source published on &lt;a href=&quot;https://github.com/MeilCli/AboutMe&quot; target=&quot;_blank&quot;&gt;GitHub&lt;/a&gt;."</summary>
        public string Copyright;

        /// <summary>"Link"</summary>
        public string Link;

        /// <summary>"Resume"</summary>
        public string Resume;

        /// <summary>"SNS"</summary>
        public string Sns;
    }
}
