name: Deploy

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: npm install
      run: npm ci
      env:
        CI: true
    - name: deploy
      run: npm run deploy
      env:
        NETLIFY_TOKEN: ${{ secrets.NETLIFY_TOKEN }}
        NETLIFY_API_ID: ${{ secrets.NETLIFY_API_ID }}
